# Generated by Django 4.2.18 on 2025-01-30 22:11

from django.db import migrations, models
from django.db import connection

# Order matters and needs to be a full list of affected views
# because mssql doesn't do cascade
DEPENDENT_VIEWS = [
    "uvwAmountClaimed", "uvwAmountRejected", "uvwAmountValuated", "uvwAmountApproved",
    "uvwClaimEntered", "uvwClaimProcessed", "uvwClaimRejected", "uvwClaimSent",
    "uvwClaimSubmitted", "uvwClaimValuated", "uvwExpenditureInsureeRange",
    "uvwHospitalAdmissions", "uvwHospitalDays", "uvwItemExpenditures", "uvwItemUtilization",
    "uvwLocations", "uvwNumberFeedbackAnswerYes", "uvwNumberFeedbackResponded",
    "uvwNumberFeedbackSent", "uvwNumberInsureeAcquired", "uvwNumberOfInsuredHouseholds",
    "uvwNumberPolicyRenewed", "uvwNumberPolicySold", "uvwOverallAssessment", "uvwPopulation",
    "uvwPremiumCollection", "uvwServiceExpenditures", "uvwServiceUtilization", "uvwVisit",
    "uvwpremiumcollection", "tblDistricts", "tblRegions", "tblVillages", "tblWards",
]

view_definitions = {}


def extract_and_drop_views(apps, schema_editor):
    # Extract
    with connection.cursor() as cursor:
        global view_definitions

        if connection.vendor == 'postgresql':
            query = """
                SELECT viewname, definition
                FROM pg_views
                WHERE schemaname = 'public' AND viewname IN %s;
            """
            cursor.execute(query, (tuple(DEPENDENT_VIEWS),))
            for viewname, viewdef in cursor.fetchall():
                view_definitions[viewname] = f'CREATE OR REPLACE VIEW "public"."{viewname}" AS {viewdef}'

        elif connection.vendor == 'microsoft':
            for view in DEPENDENT_VIEWS:
                query = f"SELECT OBJECT_DEFINITION(OBJECT_ID('{view}'))"
                cursor.execute(query)
                result = cursor.fetchone()
                if result and result[0]:
                    view_definitions[view] = result[0]
    # Drop
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            for view in DEPENDENT_VIEWS:
                cursor.execute(f'DROP VIEW IF EXISTS "public"."{view}"')
        elif connection.vendor == 'microsoft':
            for view in DEPENDENT_VIEWS:
                cursor.execute(f"IF OBJECT_ID('{view}', 'V') IS NOT NULL DROP VIEW {view};")


def recreate_views(apps, schema_editor):
    global view_definitions
    with connection.cursor() as cursor:
        for view_name in reversed(DEPENDENT_VIEWS):
            cursor.execute(view_definitions[view_name])


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
    ]

    operations = [
        migrations.RunPython(extract_and_drop_views, reverse_code=recreate_views),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, db_column='LocationCode', max_length=12, null=True),
        ),
        migrations.RunPython(recreate_views, reverse_code=extract_and_drop_views),
    ]
