# Generated by Django 4.2.18 on 2025-01-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, db_column='LocationCode', max_length=12, null=True),
        ),
    ]
